### ISSUE TITLE
No handlers could be found for logger "emails.backend.smtp.backend"

### ISSUE THREAD

**Issue by Garito** [lavr/flask-emails#3]
Could someone explain me what's happening here?

This message shows up in the logs and no email is sended. The postfix is there waiting for some love

I've added too `EMAIL_SMTP_DEBUG = True` but now debug info is showed

Thanks!

**Comment by AsafSH6** [comment]
Make sure the SMTP dict you use is not unicoded (either with u' or **future** unicode_literals)

**Comment by lavr** [comment]
Hi there!
This task is slightly outdated. Hope Garito solved his problem.
"No handlers could be found for logger ..." is not an issue, this is standard warning explained in python [docs](https://docs.python.org/3.1/library/logging.html#configuring-logging-for-a-library).
