### ISSUE TITLE
Extension flask.ext is deprecated

### ISSUE THREAD

**Issue by javierseixas** [lavr/flask-emails#8]
Since Flask version 0.11 module `flask.ext` is deprecated ([see here](https://github.com/pallets/flask/blob/0e06302c79c50a4b2dd43b2bcd6f909f8994ce5e/CHANGES#L76)), so this library is broken.

Any intention of fixing that?

**Comment by lavr** [comment]
Hi! Any intention to make PR ? ))

**Comment by javierseixas** [comment]
Touché! :stuck_out_tongue_closed_eyes: 

I'm quite new to python, but I could try...

**Comment by lavr** [comment]
May be there is not much to code, just replace `from flask.ext.emails import  X` to `from flask_emails import X`

**Comment by lavr** [comment]
#9

**Comment by javierseixas** [comment]
That's great! Thanks for updating it!
